# Build the Go Binary.
FROM golang:1.17 as service-system
ENV CGO_ENABLED 0
ARG BUILD_REF

# Copy the source code into the container.
COPY . /service

# Build the service binary.
WORKDIR /service
RUN go build -ldflags "-X main.build=${BUILD_REF}"

# Run the Go binary in Alpine linux.
FROM alpine:3.15 as alpine-service-build
ARG BUILD_DATE
ARG BUILD_REF
COPY --from=service-system /service/service /service/service
WORKDIR /service
CMD ["./service"]

LABEL org.opencontainer.image.created="${BUILD_DATE}" \
      org.opencontainer.image.title="service" \
      org.opencontainer.image.authors="Esmaeil MIRZAEE <esmaeilmirzaeeATgmailDOTcom>" \
      org.opencontainer.image.source="https://github.com/esmaeilmirzaee/service-demo" \
      org.opencontainer.image.revision="${BUILD_REF}" \
      org.opencontainer.image.vendor="The Beaver"
