# This file mainly is to open up ports
kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
nodes:
- role: control-plane
  extraPortMappings:
    - containerPort: 1337
      hostPort: 1337
    - containerPort: 1338
      hostPort: 1338
